# Generated by Django 5.0.4 on 2024-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default=" ", max_length=180),
        ),
    ]
