# Generated by Django 5.0.4 on 2024-04-24 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
    ]
