# Generated by Django 5.0.4 on 2024-04-25 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="uesr",
            new_name="user",
        ),
    ]
